/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - To quantify data and group results by specific dimensions.
    - For understanding data distribution across categories.

SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
    - LEFT JOIN
===============================================================================
*/

--Finding total customers for every country 
SELECT
	country,
	COUNT(DISTINCT customer_id) AS total_customers 
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customers DESC

--Finding total customers by gender 
SELECT 
	gender,
	COUNT(DISTINCT customer_id) AS total_customers 
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customers DESC

--Finding total products per category
SELECT 
	category,
	COUNT(DISTINCT product_id) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC

--Finding the average costs in each category
SELECT 
	category,
	AVG(product_cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC

-- Finding the total revenue generated in each category
SELECT
    prd.category,
    SUM(sales.sales) AS total_revenue
FROM gold.fact_sales sales
LEFT JOIN gold.dim_products AS prd
    ON prd.product_key = sales.product_key
GROUP BY prd.category
ORDER BY total_revenue DESC

--Finding the total revenue generated by each customer 
SELECT 
	cst.customer_key,
	cst.first_name,
	cst.last_name,
	SUM(sales.sales) AS total_revenue
FROM gold.fact_sales sales
LEFT JOIN gold.dim_customers cst
	ON cst.customer_key = sales.customer_key
GROUP BY cst.customer_key, cst.first_name, cst.last_name
ORDER BY total_revenue DESC

--Finding the ditrbution of sold items across countries
SELECT 
	cst.country,
	SUM(sales.quantity) AS total_revenue
FROM gold.fact_sales sales
LEFT JOIN gold.dim_customers cst
	ON cst.customer_key = sales.customer_key
GROUP BY cst.country
ORDER BY total_revenue DESC
